
project_id = "axuufjquzqqopjlfvnuv"

[functions.screenshot-stream]
verify_jwt = false

[functions.livepeer]
verify_jwt = false

[functions.livepeer-webhook]
verify_jwt = false

[functions.check-stream-status]
verify_jwt = false

[functions.update-thumbnail]
verify_jwt = false

[functions.process-payouts]
verify_jwt = false

[functions.process-refunds]
verify_jwt = false

[functions.paypal-sandbox]
verify_jwt = false

[functions.paypal-payout]
verify_jwt = false

[functions.capture-thumbnail]
verify_jwt = false
